# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/kartikeyasharma/Desktop/e15130/Letter/Re_ Geant4/Layer1_Beam_Mount_v0.21"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/kartikeyasharma/Desktop/e15130/Letter/Re_ Geant4/Layer1_Beam_Mount_v0.21"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/kartikeyasharma/Desktop/e15130/Letter/Re_ Geant4/Layer1_Beam_Mount_v0.21/CMakeFiles" "/Users/kartikeyasharma/Desktop/e15130/Letter/Re_ Geant4/Layer1_Beam_Mount_v0.21//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/kartikeyasharma/Desktop/e15130/Letter/Re_ Geant4/Layer1_Beam_Mount_v0.21/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named neutron_collimator

# Build rule for target.
neutron_collimator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neutron_collimator
.PHONY : neutron_collimator

# fast build rule for target.
neutron_collimator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/build
.PHONY : neutron_collimator/fast

neutron_collimator.o: neutron_collimator.cc.o
.PHONY : neutron_collimator.o

# target to build an object file
neutron_collimator.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/neutron_collimator.cc.o
.PHONY : neutron_collimator.cc.o

neutron_collimator.i: neutron_collimator.cc.i
.PHONY : neutron_collimator.i

# target to preprocess a source file
neutron_collimator.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/neutron_collimator.cc.i
.PHONY : neutron_collimator.cc.i

neutron_collimator.s: neutron_collimator.cc.s
.PHONY : neutron_collimator.s

# target to generate assembly for a file
neutron_collimator.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/neutron_collimator.cc.s
.PHONY : neutron_collimator.cc.s

src/ActionInitialization.o: src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.o

# target to build an object file
src/ActionInitialization.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.cc.o

src/ActionInitialization.i: src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.i

# target to preprocess a source file
src/ActionInitialization.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.cc.i

src/ActionInitialization.s: src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.s

# target to generate assembly for a file
src/ActionInitialization.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.cc.s

src/CCalAMaterial.o: src/CCalAMaterial.cc.o
.PHONY : src/CCalAMaterial.o

# target to build an object file
src/CCalAMaterial.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/CCalAMaterial.cc.o
.PHONY : src/CCalAMaterial.cc.o

src/CCalAMaterial.i: src/CCalAMaterial.cc.i
.PHONY : src/CCalAMaterial.i

# target to preprocess a source file
src/CCalAMaterial.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/CCalAMaterial.cc.i
.PHONY : src/CCalAMaterial.cc.i

src/CCalAMaterial.s: src/CCalAMaterial.cc.s
.PHONY : src/CCalAMaterial.s

# target to generate assembly for a file
src/CCalAMaterial.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/CCalAMaterial.cc.s
.PHONY : src/CCalAMaterial.cc.s

src/CCalMaterial.o: src/CCalMaterial.cc.o
.PHONY : src/CCalMaterial.o

# target to build an object file
src/CCalMaterial.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/CCalMaterial.cc.o
.PHONY : src/CCalMaterial.cc.o

src/CCalMaterial.i: src/CCalMaterial.cc.i
.PHONY : src/CCalMaterial.i

# target to preprocess a source file
src/CCalMaterial.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/CCalMaterial.cc.i
.PHONY : src/CCalMaterial.cc.i

src/CCalMaterial.s: src/CCalMaterial.cc.s
.PHONY : src/CCalMaterial.s

# target to generate assembly for a file
src/CCalMaterial.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/CCalMaterial.cc.s
.PHONY : src/CCalMaterial.cc.s

src/CCalMaterialFactory.o: src/CCalMaterialFactory.cc.o
.PHONY : src/CCalMaterialFactory.o

# target to build an object file
src/CCalMaterialFactory.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/CCalMaterialFactory.cc.o
.PHONY : src/CCalMaterialFactory.cc.o

src/CCalMaterialFactory.i: src/CCalMaterialFactory.cc.i
.PHONY : src/CCalMaterialFactory.i

# target to preprocess a source file
src/CCalMaterialFactory.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/CCalMaterialFactory.cc.i
.PHONY : src/CCalMaterialFactory.cc.i

src/CCalMaterialFactory.s: src/CCalMaterialFactory.cc.s
.PHONY : src/CCalMaterialFactory.s

# target to generate assembly for a file
src/CCalMaterialFactory.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/CCalMaterialFactory.cc.s
.PHONY : src/CCalMaterialFactory.cc.s

src/CCalutils.o: src/CCalutils.cc.o
.PHONY : src/CCalutils.o

# target to build an object file
src/CCalutils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/CCalutils.cc.o
.PHONY : src/CCalutils.cc.o

src/CCalutils.i: src/CCalutils.cc.i
.PHONY : src/CCalutils.i

# target to preprocess a source file
src/CCalutils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/CCalutils.cc.i
.PHONY : src/CCalutils.cc.i

src/CCalutils.s: src/CCalutils.cc.s
.PHONY : src/CCalutils.s

# target to generate assembly for a file
src/CCalutils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/CCalutils.cc.s
.PHONY : src/CCalutils.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/DetectorMap.o: src/DetectorMap.cc.o
.PHONY : src/DetectorMap.o

# target to build an object file
src/DetectorMap.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/DetectorMap.cc.o
.PHONY : src/DetectorMap.cc.o

src/DetectorMap.i: src/DetectorMap.cc.i
.PHONY : src/DetectorMap.i

# target to preprocess a source file
src/DetectorMap.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/DetectorMap.cc.i
.PHONY : src/DetectorMap.cc.i

src/DetectorMap.s: src/DetectorMap.cc.s
.PHONY : src/DetectorMap.s

# target to generate assembly for a file
src/DetectorMap.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/DetectorMap.cc.s
.PHONY : src/DetectorMap.cc.s

src/EventAction.o: src/EventAction.cc.o
.PHONY : src/EventAction.o

# target to build an object file
src/EventAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/EventAction.cc.o
.PHONY : src/EventAction.cc.o

src/EventAction.i: src/EventAction.cc.i
.PHONY : src/EventAction.i

# target to preprocess a source file
src/EventAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/EventAction.cc.i
.PHONY : src/EventAction.cc.i

src/EventAction.s: src/EventAction.cc.s
.PHONY : src/EventAction.s

# target to generate assembly for a file
src/EventAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/EventAction.cc.s
.PHONY : src/EventAction.cc.s

src/Materials.o: src/Materials.cc.o
.PHONY : src/Materials.o

# target to build an object file
src/Materials.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/Materials.cc.o
.PHONY : src/Materials.cc.o

src/Materials.i: src/Materials.cc.i
.PHONY : src/Materials.i

# target to preprocess a source file
src/Materials.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/Materials.cc.i
.PHONY : src/Materials.cc.i

src/Materials.s: src/Materials.cc.s
.PHONY : src/Materials.s

# target to generate assembly for a file
src/Materials.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/Materials.cc.s
.PHONY : src/Materials.cc.s

src/NeutronHPMessenger.o: src/NeutronHPMessenger.cc.o
.PHONY : src/NeutronHPMessenger.o

# target to build an object file
src/NeutronHPMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/NeutronHPMessenger.cc.o
.PHONY : src/NeutronHPMessenger.cc.o

src/NeutronHPMessenger.i: src/NeutronHPMessenger.cc.i
.PHONY : src/NeutronHPMessenger.i

# target to preprocess a source file
src/NeutronHPMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/NeutronHPMessenger.cc.i
.PHONY : src/NeutronHPMessenger.cc.i

src/NeutronHPMessenger.s: src/NeutronHPMessenger.cc.s
.PHONY : src/NeutronHPMessenger.s

# target to generate assembly for a file
src/NeutronHPMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/NeutronHPMessenger.cc.s
.PHONY : src/NeutronHPMessenger.cc.s

src/NeutronHPphysics.o: src/NeutronHPphysics.cc.o
.PHONY : src/NeutronHPphysics.o

# target to build an object file
src/NeutronHPphysics.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/NeutronHPphysics.cc.o
.PHONY : src/NeutronHPphysics.cc.o

src/NeutronHPphysics.i: src/NeutronHPphysics.cc.i
.PHONY : src/NeutronHPphysics.i

# target to preprocess a source file
src/NeutronHPphysics.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/NeutronHPphysics.cc.i
.PHONY : src/NeutronHPphysics.cc.i

src/NeutronHPphysics.s: src/NeutronHPphysics.cc.s
.PHONY : src/NeutronHPphysics.s

# target to generate assembly for a file
src/NeutronHPphysics.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/NeutronHPphysics.cc.s
.PHONY : src/NeutronHPphysics.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/RunAction.o: src/RunAction.cc.o
.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i
.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s
.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

src/Sample.o: src/Sample.cc.o
.PHONY : src/Sample.o

# target to build an object file
src/Sample.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/Sample.cc.o
.PHONY : src/Sample.cc.o

src/Sample.i: src/Sample.cc.i
.PHONY : src/Sample.i

# target to preprocess a source file
src/Sample.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/Sample.cc.i
.PHONY : src/Sample.cc.i

src/Sample.s: src/Sample.cc.s
.PHONY : src/Sample.s

# target to generate assembly for a file
src/Sample.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/Sample.cc.s
.PHONY : src/Sample.cc.s

src/SteppingAction.o: src/SteppingAction.cc.o
.PHONY : src/SteppingAction.o

# target to build an object file
src/SteppingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/SteppingAction.cc.o
.PHONY : src/SteppingAction.cc.o

src/SteppingAction.i: src/SteppingAction.cc.i
.PHONY : src/SteppingAction.i

# target to preprocess a source file
src/SteppingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/SteppingAction.cc.i
.PHONY : src/SteppingAction.cc.i

src/SteppingAction.s: src/SteppingAction.cc.s
.PHONY : src/SteppingAction.s

# target to generate assembly for a file
src/SteppingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/SteppingAction.cc.s
.PHONY : src/SteppingAction.cc.s

src/TrackerFluxSheet.o: src/TrackerFluxSheet.cc.o
.PHONY : src/TrackerFluxSheet.o

# target to build an object file
src/TrackerFluxSheet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/TrackerFluxSheet.cc.o
.PHONY : src/TrackerFluxSheet.cc.o

src/TrackerFluxSheet.i: src/TrackerFluxSheet.cc.i
.PHONY : src/TrackerFluxSheet.i

# target to preprocess a source file
src/TrackerFluxSheet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/TrackerFluxSheet.cc.i
.PHONY : src/TrackerFluxSheet.cc.i

src/TrackerFluxSheet.s: src/TrackerFluxSheet.cc.s
.PHONY : src/TrackerFluxSheet.s

# target to generate assembly for a file
src/TrackerFluxSheet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/TrackerFluxSheet.cc.s
.PHONY : src/TrackerFluxSheet.cc.s

src/TrackerNeutronSD.o: src/TrackerNeutronSD.cc.o
.PHONY : src/TrackerNeutronSD.o

# target to build an object file
src/TrackerNeutronSD.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/TrackerNeutronSD.cc.o
.PHONY : src/TrackerNeutronSD.cc.o

src/TrackerNeutronSD.i: src/TrackerNeutronSD.cc.i
.PHONY : src/TrackerNeutronSD.i

# target to preprocess a source file
src/TrackerNeutronSD.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/TrackerNeutronSD.cc.i
.PHONY : src/TrackerNeutronSD.cc.i

src/TrackerNeutronSD.s: src/TrackerNeutronSD.cc.s
.PHONY : src/TrackerNeutronSD.s

# target to generate assembly for a file
src/TrackerNeutronSD.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/TrackerNeutronSD.cc.s
.PHONY : src/TrackerNeutronSD.cc.s

src/physics.o: src/physics.cc.o
.PHONY : src/physics.o

# target to build an object file
src/physics.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/physics.cc.o
.PHONY : src/physics.cc.o

src/physics.i: src/physics.cc.i
.PHONY : src/physics.i

# target to preprocess a source file
src/physics.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/physics.cc.i
.PHONY : src/physics.cc.i

src/physics.s: src/physics.cc.s
.PHONY : src/physics.s

# target to generate assembly for a file
src/physics.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neutron_collimator.dir/build.make CMakeFiles/neutron_collimator.dir/src/physics.cc.s
.PHONY : src/physics.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... neutron_collimator"
	@echo "... neutron_collimator.o"
	@echo "... neutron_collimator.i"
	@echo "... neutron_collimator.s"
	@echo "... src/ActionInitialization.o"
	@echo "... src/ActionInitialization.i"
	@echo "... src/ActionInitialization.s"
	@echo "... src/CCalAMaterial.o"
	@echo "... src/CCalAMaterial.i"
	@echo "... src/CCalAMaterial.s"
	@echo "... src/CCalMaterial.o"
	@echo "... src/CCalMaterial.i"
	@echo "... src/CCalMaterial.s"
	@echo "... src/CCalMaterialFactory.o"
	@echo "... src/CCalMaterialFactory.i"
	@echo "... src/CCalMaterialFactory.s"
	@echo "... src/CCalutils.o"
	@echo "... src/CCalutils.i"
	@echo "... src/CCalutils.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/DetectorMap.o"
	@echo "... src/DetectorMap.i"
	@echo "... src/DetectorMap.s"
	@echo "... src/EventAction.o"
	@echo "... src/EventAction.i"
	@echo "... src/EventAction.s"
	@echo "... src/Materials.o"
	@echo "... src/Materials.i"
	@echo "... src/Materials.s"
	@echo "... src/NeutronHPMessenger.o"
	@echo "... src/NeutronHPMessenger.i"
	@echo "... src/NeutronHPMessenger.s"
	@echo "... src/NeutronHPphysics.o"
	@echo "... src/NeutronHPphysics.i"
	@echo "... src/NeutronHPphysics.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
	@echo "... src/Sample.o"
	@echo "... src/Sample.i"
	@echo "... src/Sample.s"
	@echo "... src/SteppingAction.o"
	@echo "... src/SteppingAction.i"
	@echo "... src/SteppingAction.s"
	@echo "... src/TrackerFluxSheet.o"
	@echo "... src/TrackerFluxSheet.i"
	@echo "... src/TrackerFluxSheet.s"
	@echo "... src/TrackerNeutronSD.o"
	@echo "... src/TrackerNeutronSD.i"
	@echo "... src/TrackerNeutronSD.s"
	@echo "... src/physics.o"
	@echo "... src/physics.i"
	@echo "... src/physics.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

