# Use this open statement to create an OpenGL view:
/vis/open TSG
# Disable auto refresh and quieten vis messages whilst scene and

# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
/vis/viewer/set/background 1 1 1
# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90 180
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector 0 -1 0
#
# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
#/vis/viewer/set/lineSegmentsPerCircle 100
#
/tracking/verbose 1
/tracking/storeTrajectory 0
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate

#/vis/modeling/trajectories/clear #removes conflicting trajectory models

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron black 8
/vis/modeling/trajectories/drawByParticleID-0/set proton  blue
/vis/modeling/trajectories/drawByParticleID-0/set ion-H[1]  cyan    # hydrogen ion
/vis/modeling/trajectories/drawByParticleID-0/set ion-C[12] orange  # carbon-12 ion
/vis/modeling/trajectories/drawByParticleID-0/set alpha yellow
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set GenericIon grey

/vis/scene/add/axes 0 0 0 15.00 cm
#/vis/scene/add/scale 40 cm cm z 1 1 1 manual 0 0 17.02 mm
